### ISSUE TITLE
AWS Account ID is masked in Notify Proton Step

### ISSUE THREAD

**Issue by warpspeed6** [aws-samples/aws-proton-terraform-github-actions-sample#20]
Ref: https://github.com/aws-actions/configure-aws-credentials/issues/304

As [configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) masks the AWS Account ID, the `--resource-arn ${{ needs.get-deployment-data.outputs.resource_arn }}` resolves to a masked (xxx) AWS_ACCOUNTID in the ARN, resulting in step failure. 

A solution would be to include mask-aws-account-id: 'no' in Configure AWS Credentials step.

```
    - name: Configure AWS Credentials
      id: assume_role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ needs.get-deployment-data.outputs.target_region }}
        role-to-assume: ${{ needs.get-deployment-data.outputs.role_arn }}
        role-session-name: TF-Github-Actions-Notify-Proton
        mask-aws-account-id: 'no'
```
